services:
  seymour:
    build:
      context: .
    ports:
      - '3000:3000'

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${SSL_CERT_PATH:-./nginx/ssl/cert.pem}:/etc/nginx/ssl/cert.pem:ro
      - ${SSL_PRIVATE_KEY_PATH:-./nginx/ssl/privkey.pem}:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - '8000:80'
      - '8001:443'
    depends_on:
      - seymour
