apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-me-seymour
  name: feed-me-seymour
spec:
  ports:
    - name: web
      port: 3000
      targetPort: 3000
  selector:
    app: feed-me-seymour
